# netlify.toml

[build]
  command = "npm run build"
  # publish = ".next"  <-- O Netlify detecta isso sozinho agora, melhor deixar ele decidir

# Configurações do Ambiente Local (Netlify Dev)
[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  autoLaunch = false

# Contexto de Desenvolvimento (Staging)
[context.develop]
  command = "npm run build"